const Questions = [
   {
      question: "What is the capital of France?",
      options: ["Berlin", "Madrid", "Paris", "Lisbon"],
      category: "Geography",
      correctAnswer: "Paris",
      difficulty: "easy",
      points: 10,
   },

   {
      question: "Who wrote 'To Kill a Mockingbird'?",
      options: ["Harper Lee", "J.K. Rowling", "Mark Twain", "Ernest Hemingway"],
      category: "Literature",
      correctAnswer: "Harper Lee",
      difficulty: "medium",
      points: 15,
   },
   {
      question: "Which planet is known as the Red Planet?",
      options: ["Earth", "Mars", "Jupiter", "Saturn"],
      category: "Geography",
      correctAnswer: "Mars",
      difficulty: "easy",
      points: 10,
   },
   {
      question: "What is the smallest country in the world?",
      options: ["Vatican City", "Monaco", "San Marino", "Liechtenstein"],
      category: "Geography",
      correctAnswer: "Vatican City",
      difficulty: "medium",
      points: 15,
   },
   {
      question: "Who painted the Mona Lisa?",
      options: [
         "Vincent van Gogh",
         "Claude Monet",
         "Pablo Picasso",
         "Leonardo da Vinci",
      ],
      category: "Art",
      correctAnswer: "Leonardo da Vinci",
      difficulty: "easy",
      points: 10,
   },
   {
      question: "In what year did the Titanic sink?",
      options: ["1912", "1915", "1920", "1905"],
      category: "History",
      correctAnswer: "1912",
      difficulty: "medium",
      points: 15,
   },
   {
      question: "Who was the first President of the United States?",
      options: [
         "Thomas Jefferson",
         "Abraham Lincoln",
         "George Washington",
         "John Adams",
      ],
      category: "History",
      correctAnswer: "George Washington",
      difficulty: "easy",
      points: 10,
   },
   {
      question: "What is the longest river in the world?",
      options: ["Nile", "Amazon", "Yangtze", "Mississippi"],
      category: "Geography",
      correctAnswer: "Nile",
      difficulty: "hard",
      points: 20,
   },
   {
      question: "What is the chemical symbol for gold?",
      options: ["Au", "Ag", "Fe", "Pb"],
      category: "Science",
      correctAnswer: "Au",
      difficulty: "easy",
      points: 10,
   },
   {
      question: "Who is known as the father of modern physics?",
      options: [
         "Isaac Newton",
         "Albert Einstein",
         "Niels Bohr",
         "Galileo Galilei",
      ],
      category: "History",
      correctAnswer: "Albert Einstein",
      difficulty: "hard",
      points: 20,
   },
   {
      question: "What is the capital of Japan?",
      options: ["Seoul", "Beijing", "Tokyo", "Bangkok"],
      category: "Geography",
      correctAnswer: "Tokyo",
      difficulty: "easy",
      points: 10,
   },
   {
      question: "In which year did World War II end?",
      options: ["1942", "1945", "1948", "1950"],
      category: "History",
      correctAnswer: "1945",
      difficulty: "medium",
      points: 15,
   },
   {
      question: "What is the largest ocean on Earth?",
      options: [
         "Atlantic Ocean",
         "Indian Ocean",
         "Arctic Ocean",
         "Pacific Ocean",
      ],
      category: "Geography",
      correctAnswer: "Pacific Ocean",
      difficulty: "easy",
      points: 10,
   },
   {
      question: "Who discovered penicillin?",
      options: [
         "Marie Curie",
         "Alexander Fleming",
         "Louis Pasteur",
         "Joseph Lister",
      ],
      category: "Science",
      correctAnswer: "Alexander Fleming",
      difficulty: "medium",
      points: 15,
   },
   {
      question: "What is the hardest natural substance on Earth?",
      options: ["Gold", "Iron", "Diamond", "Platinum"],
      category: "Geography",
      correctAnswer: "Diamond",
      difficulty: "easy",
      points: 10,
   },
   {
      question: "Which country hosted the 2016 Summer Olympics?",
      options: ["China", "Brazil", "UK", "USA"],
      category: "History",
      correctAnswer: "Brazil",
      difficulty: "medium",
      points: 15,
   },
   {
      question: "What is the main ingredient in guacamole?",
      options: ["Tomato", "Pepper", "Onion", "Avocado"],
      category: "Science",
      correctAnswer: "Avocado",
      difficulty: "easy",
      points: 10,
   },
   {
      question: "Who wrote the play 'Romeo and Juliet'?",
      options: [
         "Oscar Wilde",
         "William Shakespeare",
         "George Bernard Shaw",
         "Tennessee Williams",
      ],
      category: "History",
      correctAnswer: "William Shakespeare",
      difficulty: "easy",
      points: 10,
   },
   {
      question: "What is the largest planet in our solar system?",
      options: ["Earth", "Saturn", "Jupiter", "Mars"],
      category: "Geography",
      correctAnswer: "Jupiter",
      difficulty: "easy",
      points: 10,
   },
   {
      question: "Which element has the atomic number 1?",
      options: ["Helium", "Oxygen", "Hydrogen", "Nitrogen"],
      category: "Science",
      correctAnswer: "Hydrogen",
      difficulty: "easy",
      points: 10,
   },
];

export default Questions;
