const Questions = [
   {
      question: "What is the capital of France?",
      options: ["Berlin", "Madrid", "Paris", "Lisbon"],
      category: "Cinema",
      correctAnswer: "Paris",
      difficulty: "Hard",
      points: 10,
      background: "/BG/cinemabg.png",
   },
   {
      question: "Who wrote 'To Kill a Mockingbird'?",
      options: ["Harper Lee", "J.K. Rowling", "Mark Twain", "Ernest Hemingway"],
      category: "Sports",
      correctAnswer: "Harper Lee",
      difficulty: "Medium",
      points: 15,
      background: "/BG/sportsbg.png",
   },
   {
      question: "Who has won the most ballon d'ors?",
      options: [
         "Lionel Messi",
         "Cristiano Ronaldo",
         "Michel Platini",
         "Ronaldo Nazario de Lima",
      ],
      category: "Sports",
      correctAnswer: "Lionel Messi",
      difficulty: "medium",
      points: 15,
      background: "/BG/sportsbg.png",
   },

   {
      question: "Who painted the Mona Lisa?",
      options: [
         "Vincent van Gogh",
         "Claude Monet",
         "Pablo Picasso",
         "Leonardo da Vinci",
      ],
      category: "Art",
      correctAnswer: "Leonardo da Vinci",
      difficulty: "Easy",
      points: 10,
      background: "/BG/generalbg.png",
   },
   {
      question: "In what year did the Titanic sink?",
      options: ["1912", "1915", "1920", "1905"],
      category: "History",
      correctAnswer: "1912",
      difficulty: "Medium",
      points: 15,
      background: "/BG/historybg.png",
   },
   {
      question: "Who was the first President of the United States?",
      options: [
         "Thomas Jefferson",
         "Abraham Lincoln",
         "George Washington",
         "John Adams",
      ],
      category: "History",
      correctAnswer: "George Washington",
      difficulty: "Hard",
      points: 20,
      background: "/BG/historybg.png",
   },

   {
      question: "What is the chemical symbol for gold?",
      options: ["Au", "Ag", "Fe", "Pb"],
      category: "Science",
      correctAnswer: "Au",
      difficulty: "Hard",
      points: 10,
      background: "/BG/chemistrybg.png",
   },
   {
      question: "Who is known as the father of modern physics?",
      options: [
         "Isaac Newton",
         "Albert Einstein",
         "Niels Bohr",
         "Galileo Galilei",
      ],
      category: "History",
      correctAnswer: "Albert Einstein",
      difficulty: "Hard",
      points: 20,
      background: "/BG/historybg.png",
   },
   {
      question: "What is the capital of Japan?",
      options: ["Seoul", "Beijing", "Tokyo", "Bangkok"],
      category: "Geography",
      correctAnswer: "Tokyo",
      difficulty: "Hard",
      points: 10,
      background: "/BG/historybg.png",
   },
   {
      question: "In which year did World War II end?",
      options: ["1942", "1945", "1948", "1950"],
      category: "History",
      correctAnswer: "1945",
      difficulty: "Medium",
      points: 15,
      background: "/BG/historybg.png",
   },
   {
      question: "What is the largest ocean on Earth?",
      options: [
         "Atlantic Ocean",
         "Indian Ocean",
         "Arctic Ocean",
         "Pacific Ocean",
      ],
      category: "Geography",
      correctAnswer: "Pacific Ocean",
      difficulty: "Hard",
      points: 10,
      background: "/BG/geographybg.png",
   },
   {
      question: "Who discovered penicillin?",
      options: [
         "Marie Curie",
         "Alexander Fleming",
         "Louis Pasteur",
         "Joseph Lister",
      ],
      category: "Science",
      correctAnswer: "Alexander Fleming",
      difficulty: "Medium",
      points: 15,
      background: "/BG/chemistrybg.png",
   },

   {
      question: "Which country hosted the 2016 Summer Olympics?",
      options: ["China", "Brazil", "UK", "USA"],
      category: "History",
      correctAnswer: "Brazil",
      difficulty: "Medium",
      points: 15,
      background: "/BG/historybg.png",
   },
   {
      question: "What is the main ingredient in guacamole?",
      options: ["Tomato", "Pepper", "Onion", "Avocado"],
      category: "Science",
      correctAnswer: "Avocado",
      difficulty: "Easy",
      points: 10,
      background: "/BG/historybg.png",
   },
   {
      question: "Who wrote the play 'Romeo and Juliet'?",
      options: [
         "Oscar Wilde",
         "William Shakespeare",
         "George Bernard Shaw",
         "Tennessee Williams",
      ],
      category: "History",
      correctAnswer: "William Shakespeare",
      difficulty: "Easy",
      points: 10,
      background: "/BG/historybg.png",
   },
   {
      question: "What is the largest planet in our solar system?",
      options: ["Earth", "Saturn", "Jupiter", "Mars"],
      category: "Geography",
      correctAnswer: "Jupiter",
      difficulty: "Easy",
      points: 10,
      background: "/BG/historybg.png",
   },

   {
      question: "Which country's flag is this?",
      options: ["Yemen", "Oman", "Saudi Arabia", "United Arab Emirates"],
      image: "/Flags/ye.png",
      category: "Geography",
      correctAnswer: "Yemen",
      difficulty: "Hard",
      points: 10,
      background: "/BG/geographybg.png",
   },
   {
      question: "Which country's flag is this?",
      options: ["Yemen", "Oman", "Saudi Arabia", "United Arab Emirates"],
      image: "/Flags/af.png",
      category: "Geography",
      correctAnswer: "Yemen",
      difficulty: "Hard",
      points: 10,
      background: "/BG/geographybg.png",
   },
   {
      question: "Which country's flag is this?",
      options: ["Yemen", "Oman", "Saudi Arabia", "United Arab Emirates"],
      image: "/Flags/cz.png",
      category: "Geography",
      correctAnswer: "Yemen",
      difficulty: "Hard",
      points: 10,
      background: "/BG/geographybg.png",
   },
   {
      question: "Which country's flag is this?",
      options: ["Yemen", "Oman", "Saudi Arabia", "United Arab Emirates"],
      image: "/Flags/ec.png",
      category: "Geography",
      correctAnswer: "Yemen",
      difficulty: "Hard",
      points: 10,
      background: "/BG/geographybg.png",
   },
   {
      question: "Which country's flag is this?",
      options: ["Yemen", "Oman", "Saudi Arabia", "United Arab Emirates"],
      image: "/Flags/fi.png",
      category: "Geography",
      correctAnswer: "Yemen",
      difficulty: "Hard",
      points: 10,
      background: "/BG/geographybg.png",
   },
   {
      question: "ASL PLS?",
      options: ["Yemen", "Oman", "Saudi Arabia", "United Arab Emirates"],
      image: "/Flags/fi.png",
      category: "Geography",
      correctAnswer: "Yemen",
      difficulty: "Hardcore",
      points: 10,
      background: "/BG/geographybg.png",
   },
];

export default Questions;
